name: spacetime-dev
channels:
  - conda-forge
dependencies:
  # Minimal environment to run the notebook in contributors/friedrich
  - geopandas
  - xarray
  - rioxarray
  - dask
  - zarr
  - gpytorch
  - scikit-learn
  - pykrige
  - gstools
  - s3fs  # To access S3